name: Auto Deploy to Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

# tf is docker /s
jobs:
  autodeploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: adopt
      - name: Grant Execution Permission for Gradle
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload jar
        uses: actions/upload-artifact@v1.0.0
        with:
          path: /build/libs/DEPLOYMENT.jar
